from mozdns.tests.model_tests import *  # noqa
from mozdns.domain.view_tests import *  # noqa
from mozdns.soa.view_tests import *  # noqa
from mozdns.tests.view_tests import *  # noqa
from mozdns.record.tests.tests import *  # noqa
from mozdns.api.tests.all import *  # noqa
from mozdns.mozbind.tests.all import *  # noqa
from mozdns.create_zone.tests import *  # noqa
from mozdns.delete_zone.tests import *  # noqa
