from mozdns.address_record.tests import *
from mozdns.domain.tests.all import *
from mozdns.ip.tests import *
from mozdns.nameserver.tests import *
from mozdns.nameserver.tests import *
from mozdns.ptr.tests import *
from mozdns.soa.tests import *
from mozdns.mx.tests import *
from mozdns.srv.tests import *
from mozdns.cname.tests import *
from mozdns.ip.tests import *
from mozdns.txt.tests import *
from mozdns.sshfp.tests import *
