from core.registration.static.tests.basic import *  # noqa
from core.registration.static.tests.A_tests import *  # noqa
from core.registration.static.tests.aux_attrs import *  # noqa
from core.registration.static.tests.PTR_tests import *  # noqa
from core.registration.static.tests.ipv6_basic import *  # noqa
from core.registration.static.tests.CNAME_tests import *  # noqa
from core.registration.static.tests.deletetion import *  # noqa
from core.registration.static.tests.system_integration import *  # noqa
from core.registration.static.tests.decommission import *  # noqa
