SYSADMIN_REPO = ''
external = [
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/1billionplusu.com',
		'zone_name': '1billionplusu.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/1billionplusyou.com',
		'zone_name': '1billionplusyou.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/allizom.org',
		'zone_name': 'allizom.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/brendaneich.com',
		'zone_name': 'brendaneich.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/brendaneich.org',
		'zone_name': 'brendaneich.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/bugzilla.org',
		'zone_name': 'bugzilla.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/buildyourownbrowser.com',
		'zone_name': 'buildyourownbrowser.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.206.80.95',
		'zone_name': '206.80.95',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.223.202.6',
		'zone_name': '223.202.6',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.2620-0101-800.ip6.arpa',
		'zone_name': '2620-0101-800.ip6.arpa',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.208',
		'zone_name': '63.245.208',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.209',
		'zone_name': '63.245.209',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.210',
		'zone_name': '63.245.210',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.211',
		'zone_name': '63.245.211',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.212',
		'zone_name': '63.245.212',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.213',
		'zone_name': '63.245.213',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.214',
		'zone_name': '63.245.214',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.215',
		'zone_name': '63.245.215',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.216',
		'zone_name': '63.245.216',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.217',
		'zone_name': '63.245.217',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.218',
		'zone_name': '63.245.218',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.219',
		'zone_name': '63.245.219',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.220',
		'zone_name': '63.245.220',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.221',
		'zone_name': '63.245.221',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.222',
		'zone_name': '63.245.222',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.63.245.223',
		'zone_name': '63.245.223',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.64.13.144',
		'zone_name': '64.13.144',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.64.13.145',
		'zone_name': '64.13.145',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.64.13.146',
		'zone_name': '64.13.146',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/db.64.13.147',
		'zone_name': '64.13.147',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/drumbeat.org',
		'zone_name': 'drumbeat.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/ecmascript.org',
		'zone_name': 'ecmascript.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/extendfirefox.com',
		'zone_name': 'extendfirefox.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/fightagainstboredom.com',
		'zone_name': 'fightagainstboredom.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/fightagainstboredom.org',
		'zone_name': 'fightagainstboredom.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/firefox.com',
		'zone_name': 'firefox.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/firefoxflicks.com',
		'zone_name': 'firefoxflicks.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/firefox.lt',
		'zone_name': 'firefox.lt',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/firefoxnote.jp',
		'zone_name': 'firefoxnote.jp',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/firefoxparty.com',
		'zone_name': 'firefoxparty.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/firefoxtweetmachine.com',
		'zone_name': 'firefoxtweetmachine.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/funnyfox.org',
		'zone_name': 'funnyfox.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/getfirebug.com',
		'zone_name': 'getfirebug.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/getpersonas.com',
		'zone_name': 'getpersonas.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/impactmozilla.com',
		'zone_name': 'impactmozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/learningfreedomandtheweb.org',
		'zone_name': 'learningfreedomandtheweb.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.com',
		'zone_name': 'mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozillacorp.com',
		'zone_name': 'mozillacorp.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.cz',
		'zone_name': 'mozilla.cz',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.de',
		'zone_name': 'mozilla.de',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozillademos.org',
		'zone_name': 'mozillademos.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla-europe.org',
		'zone_name': 'mozilla-europe.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozillafoundation.org',
		'zone_name': 'mozillafoundation.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozillalabs.com',
		'zone_name': 'mozillalabs.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.lk',
		'zone_name': 'mozilla.lk',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.net',
		'zone_name': 'mozilla.net',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.org',
		'zone_name': 'mozilla.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozillaparty.com',
		'zone_name': 'mozillaparty.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.ro',
		'zone_name': 'mozilla.ro',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozillaservice.org',
		'zone_name': 'mozillaservice.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla-world.org',
		'zone_name': 'mozilla-world.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozillians.org',
		'zone_name': 'mozillians.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozqa.com',
		'zone_name': 'mozqa.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/onebillionplusu.com',
		'zone_name': 'onebillionplusu.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/onebillionplusyou.com',
		'zone_name': 'onebillionplusyou.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/openattribute.com',
		'zone_name': 'openattribute.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/opentochoice.org',
		'zone_name': 'opentochoice.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/operationfirefox.com',
		'zone_name': 'operationfirefox.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/phx.mozilla.com',
		'zone_name': 'phx.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/priorartshare.org',
		'zone_name': 'priorartshare.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/producefirefox.com',
		'zone_name': 'producefirefox.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/publicsuffix.org',
		'zone_name': 'publicsuffix.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/redirects-to-mozilla-europe.org',
		'zone_name': 'redirects-to-mozilla-europe.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/redirects-to-mozilla-europe.org-nomail',
		'zone_name': 'redirects-to-mozilla-europe.org-nomail',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/redirects-to-www.mozilla.com',
		'zone_name': 'redirects-to-www.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/redirects-to-www.mozilla.org',
		'zone_name': 'redirects-to-www.mozilla.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/rockyourfirefox.com',
		'zone_name': 'rockyourfirefox.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/spreadfirefox.com',
		'zone_name': 'spreadfirefox.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/testswarm.com',
		'zone_name': 'testswarm.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/thunderbird.net',
		'zone_name': 'thunderbird.net',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/webifyme.org',
		'zone_name': 'webifyme.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/webmademovies.org',
		'zone_name': 'webmademovies.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/webofwonder.org',
		'zone_name': 'webofwonder.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/worldfirefoxday.com',
		'zone_name': 'worldfirefoxday.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
]
