SYSADMIN_REPO = ''
mozilla_com_dcs = [
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/ad/public',
		'zone_name': 'ad.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/ad/private',
		'zone_name': 'ad.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/akl1/public',
		'zone_name': 'akl1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/akl1/private',
		'zone_name': 'akl1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/ams1/public',
		'zone_name': 'ams1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/ams1/private',
		'zone_name': 'ams1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/any1/public',
		'zone_name': 'any1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/any1/private',
		'zone_name': 'any1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/lon1/public',
		'zone_name': 'lon1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/lon1/private',
		'zone_name': 'lon1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/mtv1/public',
		'zone_name': 'mtv1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/mtv1/private',
		'zone_name': 'mtv1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/pao1/public',
		'zone_name': 'pao1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/pao1/private',
		'zone_name': 'pao1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/par1/public',
		'zone_name': 'par1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/par1/private',
		'zone_name': 'par1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/par2/public',
		'zone_name': 'par2.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/par2/private',
		'zone_name': 'par2.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/pek1/public',
		'zone_name': 'pek1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/pek1/private',
		'zone_name': 'pek1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/pek2/public',
		'zone_name': 'pek2.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/pek2/private',
		'zone_name': 'pek2.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/phx1/public',
		'zone_name': 'phx1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/phx1/private',
		'zone_name': 'phx1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/scl1/public',
		'zone_name': 'scl1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/scl1/private',
		'zone_name': 'scl1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/scl2/public',
		'zone_name': 'scl2.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/scl2/private',
		'zone_name': 'scl2.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/scl3/public',
		'zone_name': 'scl3.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/scl3/private',
		'zone_name': 'scl3.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/services/public',
		'zone_name': 'services.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/services/private',
		'zone_name': 'services.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/sfo1/public',
		'zone_name': 'sfo1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/sfo1/private',
		'zone_name': 'sfo1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/sjc1/public',
		'zone_name': 'sjc1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/sjc1/private',
		'zone_name': 'sjc1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/sjc2/public',
		'zone_name': 'sjc2.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/sjc2/private',
		'zone_name': 'sjc2.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/tor1/public',
		'zone_name': 'tor1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/tor1/private',
		'zone_name': 'tor1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/tpe1/public',
		'zone_name': 'tpe1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/tpe1/private',
		'zone_name': 'tpe1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/weave/public',
		'zone_name': 'weave.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/weave/private',
		'zone_name': 'weave.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/yvr1/public',
		'zone_name': 'yvr1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/yvr1/private',
		'zone_name': 'yvr1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/phx1/corp/public',
		'zone_name': 'corp.phx1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/mozilla.com/phx1/corp/private',
		'zone_name': 'corp.phx1.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
]
