SYSADMIN_REPO = ''
phx = [
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/2.8.10.in-addr.arpa',
		'zone_name': '2.8.10',
		'name_reversed': bool('True'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/3.8.10.in-addr.arpa',
		'zone_name': '3.8.10',
		'name_reversed': bool('True'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/76.8.10.in-addr.arpa',
		'zone_name': '76.8.10',
		'name_reversed': bool('True'),
		'direction': 'r',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.com',
		'zone_name': 'mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/mozilla.org',
		'zone_name': 'mozilla.org',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/external/phx.mozilla.com',
		'zone_name': 'phx.mozilla.com',
		'name_reversed': bool('False'),
		'direction': 'f',
		'view': 'public',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
]
