SYSADMIN_REPO = ''
private_reverse = [
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.0/10.0.0',
		'zone_name': '10.0.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.0/10.0.22',
		'zone_name': '10.0.22',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.0/10.0.250',
		'zone_name': '10.0.250',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.0',
		'zone_name': '10.10.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.1',
		'zone_name': '10.10.1',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.10',
		'zone_name': '10.10.10',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.11',
		'zone_name': '10.10.11',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.12',
		'zone_name': '10.10.12',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.14',
		'zone_name': '10.10.14',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.16',
		'zone_name': '10.10.16',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.17',
		'zone_name': '10.10.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.2',
		'zone_name': '10.10.2',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.10/10.10.3',
		'zone_name': '10.10.3',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.110/10.110.4',
		'zone_name': '10.110.4',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.110/10.110.5',
		'zone_name': '10.110.5',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.110/10.110.6',
		'zone_name': '10.110.6',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.110/10.110.7',
		'zone_name': '10.110.7',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.110/10.110.8',
		'zone_name': '10.110.8',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12',
		'zone_name': '10.12',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.0',
		'zone_name': '10.12.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.17',
		'zone_name': '10.12.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.20',
		'zone_name': '10.12.20',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.40',
		'zone_name': '10.12.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.41',
		'zone_name': '10.12.41',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.47',
		'zone_name': '10.12.47',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.48',
		'zone_name': '10.12.48',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.49',
		'zone_name': '10.12.49',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.50',
		'zone_name': '10.12.50',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.51',
		'zone_name': '10.12.51',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.52',
		'zone_name': '10.12.52',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.53',
		'zone_name': '10.12.53',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.54',
		'zone_name': '10.12.54',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.55',
		'zone_name': '10.12.55',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.69',
		'zone_name': '10.12.69',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.12/10.12.75',
		'zone_name': '10.12.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.0',
		'zone_name': '10.14.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.1',
		'zone_name': '10.14.1',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.10',
		'zone_name': '10.14.10',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.101',
		'zone_name': '10.14.101',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.102',
		'zone_name': '10.14.102',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.103',
		'zone_name': '10.14.103',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.104',
		'zone_name': '10.14.104',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.105',
		'zone_name': '10.14.105',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.106',
		'zone_name': '10.14.106',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.107',
		'zone_name': '10.14.107',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.108',
		'zone_name': '10.14.108',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.109',
		'zone_name': '10.14.109',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.11',
		'zone_name': '10.14.11',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.110',
		'zone_name': '10.14.110',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.12',
		'zone_name': '10.14.12',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.14',
		'zone_name': '10.14.14',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.2',
		'zone_name': '10.14.2',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.20',
		'zone_name': '10.14.20',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.200',
		'zone_name': '10.14.200',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.201',
		'zone_name': '10.14.201',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.202',
		'zone_name': '10.14.202',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.203',
		'zone_name': '10.14.203',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.205',
		'zone_name': '10.14.205',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.210',
		'zone_name': '10.14.210',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.211',
		'zone_name': '10.14.211',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.212',
		'zone_name': '10.14.212',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.214',
		'zone_name': '10.14.214',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.216',
		'zone_name': '10.14.216',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.220',
		'zone_name': '10.14.220',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.225',
		'zone_name': '10.14.225',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.230',
		'zone_name': '10.14.230',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.231',
		'zone_name': '10.14.231',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.232',
		'zone_name': '10.14.232',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.234',
		'zone_name': '10.14.234',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.236',
		'zone_name': '10.14.236',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.14/10.14.3',
		'zone_name': '10.14.3',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.16/10.16',
		'zone_name': '10.16',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.18/10.18',
		'zone_name': '10.18',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.2/10.2.0',
		'zone_name': '10.2.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.2/10.2.171',
		'zone_name': '10.2.171',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.2/10.2.77',
		'zone_name': '10.2.77',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.0',
		'zone_name': '10.20.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.1',
		'zone_name': '10.20.1',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.2',
		'zone_name': '10.20.2',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.3',
		'zone_name': '10.20.3',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.60',
		'zone_name': '10.20.60',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.70',
		'zone_name': '10.20.70',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.74',
		'zone_name': '10.20.74',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.75',
		'zone_name': '10.20.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.77',
		'zone_name': '10.20.77',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.20/10.20.81',
		'zone_name': '10.20.81',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.0',
		'zone_name': '10.22.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.1',
		'zone_name': '10.22.1',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.110',
		'zone_name': '10.22.110',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.111',
		'zone_name': '10.22.111',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.112',
		'zone_name': '10.22.112',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.113',
		'zone_name': '10.22.113',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.114',
		'zone_name': '10.22.114',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.115',
		'zone_name': '10.22.115',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.2',
		'zone_name': '10.22.2',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.24',
		'zone_name': '10.22.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.25',
		'zone_name': '10.22.25',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.26',
		'zone_name': '10.22.26',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.27',
		'zone_name': '10.22.27',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.28',
		'zone_name': '10.22.28',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.29',
		'zone_name': '10.22.29',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.3',
		'zone_name': '10.22.3',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.30',
		'zone_name': '10.22.30',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.31',
		'zone_name': '10.22.31',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.32',
		'zone_name': '10.22.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.33',
		'zone_name': '10.22.33',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.4',
		'zone_name': '10.22.4',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.60',
		'zone_name': '10.22.60',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.62',
		'zone_name': '10.22.62',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.69',
		'zone_name': '10.22.69',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.70',
		'zone_name': '10.22.70',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.72',
		'zone_name': '10.22.72',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.74',
		'zone_name': '10.22.74',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.75',
		'zone_name': '10.22.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.8',
		'zone_name': '10.22.8',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.80',
		'zone_name': '10.22.80',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.81',
		'zone_name': '10.22.81',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.83',
		'zone_name': '10.22.83',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.84',
		'zone_name': '10.22.84',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.22/10.22.85',
		'zone_name': '10.22.85',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.0',
		'zone_name': '10.24.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.1',
		'zone_name': '10.24.1',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.2',
		'zone_name': '10.24.2',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.70',
		'zone_name': '10.24.70',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.74',
		'zone_name': '10.24.74',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.75',
		'zone_name': '10.24.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.77',
		'zone_name': '10.24.77',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.8',
		'zone_name': '10.24.8',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.24/10.24.80',
		'zone_name': '10.24.80',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.242/10.242.0',
		'zone_name': '10.242.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.242/10.242.17',
		'zone_name': '10.242.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.242/10.242.24',
		'zone_name': '10.242.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.242/10.242.32',
		'zone_name': '10.242.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.242/10.242.40',
		'zone_name': '10.242.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.242/10.242.75',
		'zone_name': '10.242.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.243/10.243.0',
		'zone_name': '10.243.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.243/10.243.17',
		'zone_name': '10.243.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.243/10.243.24',
		'zone_name': '10.243.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.243/10.243.32',
		'zone_name': '10.243.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.243/10.243.40',
		'zone_name': '10.243.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.243/10.243.72',
		'zone_name': '10.243.72',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.243/10.243.75',
		'zone_name': '10.243.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.244/10.244.0',
		'zone_name': '10.244.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.244/10.244.17',
		'zone_name': '10.244.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.244/10.244.24',
		'zone_name': '10.244.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.244/10.244.32',
		'zone_name': '10.244.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.244/10.244.40',
		'zone_name': '10.244.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.244/10.244.75',
		'zone_name': '10.244.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.245/10.245.0',
		'zone_name': '10.245.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.245/10.245.17',
		'zone_name': '10.245.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.245/10.245.24',
		'zone_name': '10.245.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.245/10.245.32',
		'zone_name': '10.245.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.245/10.245.40',
		'zone_name': '10.245.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.245/10.245.75',
		'zone_name': '10.245.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.246/10.246.0',
		'zone_name': '10.246.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.246/10.246.17',
		'zone_name': '10.246.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.246/10.246.24',
		'zone_name': '10.246.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.246/10.246.32',
		'zone_name': '10.246.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.246/10.246.40',
		'zone_name': '10.246.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.246/10.246.75',
		'zone_name': '10.246.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.247/10.247.0',
		'zone_name': '10.247.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.247/10.247.17',
		'zone_name': '10.247.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.247/10.247.24',
		'zone_name': '10.247.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.247/10.247.32',
		'zone_name': '10.247.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.247/10.247.40',
		'zone_name': '10.247.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.247/10.247.75',
		'zone_name': '10.247.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.248/10.248.0',
		'zone_name': '10.248.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.248/10.248.17',
		'zone_name': '10.248.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.248/10.248.24',
		'zone_name': '10.248.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.248/10.248.32',
		'zone_name': '10.248.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.248/10.248.40',
		'zone_name': '10.248.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.248/10.248.72',
		'zone_name': '10.248.72',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.248/10.248.75',
		'zone_name': '10.248.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.0',
		'zone_name': '10.250.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.1',
		'zone_name': '10.250.1',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.10',
		'zone_name': '10.250.10',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.120',
		'zone_name': '10.250.120',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.128',
		'zone_name': '10.250.128',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.16',
		'zone_name': '10.250.16',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.17',
		'zone_name': '10.250.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.18',
		'zone_name': '10.250.18',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.19',
		'zone_name': '10.250.19',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.2',
		'zone_name': '10.250.2',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.20',
		'zone_name': '10.250.20',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.21',
		'zone_name': '10.250.21',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.22',
		'zone_name': '10.250.22',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.23',
		'zone_name': '10.250.23',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.3',
		'zone_name': '10.250.3',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.32',
		'zone_name': '10.250.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.33',
		'zone_name': '10.250.33',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.34',
		'zone_name': '10.250.34',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.35',
		'zone_name': '10.250.35',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.36',
		'zone_name': '10.250.36',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.37',
		'zone_name': '10.250.37',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.38',
		'zone_name': '10.250.38',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.39',
		'zone_name': '10.250.39',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.4',
		'zone_name': '10.250.4',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.48',
		'zone_name': '10.250.48',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.49',
		'zone_name': '10.250.49',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.5',
		'zone_name': '10.250.5',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.50',
		'zone_name': '10.250.50',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.51',
		'zone_name': '10.250.51',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.6',
		'zone_name': '10.250.6',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.64',
		'zone_name': '10.250.64',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.65',
		'zone_name': '10.250.65',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.7',
		'zone_name': '10.250.7',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.73',
		'zone_name': '10.250.73',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.250/10.250.75',
		'zone_name': '10.250.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.251/10.251.0',
		'zone_name': '10.251.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.251/10.251.17',
		'zone_name': '10.251.17',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.251/10.251.24',
		'zone_name': '10.251.24',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.251/10.251.32',
		'zone_name': '10.251.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.251/10.251.40',
		'zone_name': '10.251.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.251/10.251.75',
		'zone_name': '10.251.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.253/10.253.1',
		'zone_name': '10.253.1',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.10',
		'zone_name': '10.26.10',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.11',
		'zone_name': '10.26.11',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.12',
		'zone_name': '10.26.12',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.13',
		'zone_name': '10.26.13',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.14',
		'zone_name': '10.26.14',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.15',
		'zone_name': '10.26.15',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.36',
		'zone_name': '10.26.36',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.37',
		'zone_name': '10.26.37',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.38',
		'zone_name': '10.26.38',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.39',
		'zone_name': '10.26.39',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.40',
		'zone_name': '10.26.40',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.41',
		'zone_name': '10.26.41',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.42',
		'zone_name': '10.26.42',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.43',
		'zone_name': '10.26.43',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.44',
		'zone_name': '10.26.44',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.45',
		'zone_name': '10.26.45',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.46',
		'zone_name': '10.26.46',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.47',
		'zone_name': '10.26.47',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.48',
		'zone_name': '10.26.48',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.49',
		'zone_name': '10.26.49',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.50',
		'zone_name': '10.26.50',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.51',
		'zone_name': '10.26.51',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.52',
		'zone_name': '10.26.52',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.53',
		'zone_name': '10.26.53',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.54',
		'zone_name': '10.26.54',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.55',
		'zone_name': '10.26.55',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.56',
		'zone_name': '10.26.56',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.57',
		'zone_name': '10.26.57',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.58',
		'zone_name': '10.26.58',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.59',
		'zone_name': '10.26.59',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.60',
		'zone_name': '10.26.60',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.61',
		'zone_name': '10.26.61',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.62',
		'zone_name': '10.26.62',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.63',
		'zone_name': '10.26.63',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.64',
		'zone_name': '10.26.64',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.65',
		'zone_name': '10.26.65',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.66',
		'zone_name': '10.26.66',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.67',
		'zone_name': '10.26.67',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.74',
		'zone_name': '10.26.74',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.75',
		'zone_name': '10.26.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.8',
		'zone_name': '10.26.8',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.26/10.26.9',
		'zone_name': '10.26.9',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.0',
		'zone_name': '10.8.0',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.1',
		'zone_name': '10.8.1',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.10',
		'zone_name': '10.8.10',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.100',
		'zone_name': '10.8.100',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.101',
		'zone_name': '10.8.101',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.11',
		'zone_name': '10.8.11',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.110',
		'zone_name': '10.8.110',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.120',
		'zone_name': '10.8.120',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.121',
		'zone_name': '10.8.121',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.2',
		'zone_name': '10.8.2',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.3',
		'zone_name': '10.8.3',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.32',
		'zone_name': '10.8.32',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.33',
		'zone_name': '10.8.33',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.60',
		'zone_name': '10.8.60',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.62',
		'zone_name': '10.8.62',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.69',
		'zone_name': '10.8.69',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.70',
		'zone_name': '10.8.70',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.72',
		'zone_name': '10.8.72',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.73',
		'zone_name': '10.8.73',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.74',
		'zone_name': '10.8.74',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.75',
		'zone_name': '10.8.75',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.76',
		'zone_name': '10.8.76',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.80',
		'zone_name': '10.8.80',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.81',
		'zone_name': '10.8.81',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.82',
		'zone_name': '10.8.82',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.83',
		'zone_name': '10.8.83',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.84',
		'zone_name': '10.8.84',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
	{
		'path':'/home/juber/sysadmins/dnsconfig/zones/in-addr/10.8/10.8.85',
		'zone_name': '10.8.85',
		'name_reversed': bool('False'),
		'direction': 'r',
		'view': 'private',
		'relative_path': SYSADMIN_REPO + '/dnsconfig/',
	},
]
